name: Integration Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Build Chaos Mesh Build Env
        if: ${{ github.event.pull_request }}
        env:
          IMAGE_BUILD_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-build-env-image') }}
        run: |
          if [ "${IMAGE_BUILD_ENV_BUILD}" = "true" ] ; then
            export IMAGE_BUILD_ENV_BUILD=1; 
          else 
            export IMAGE_BUILD_ENV_BUILD=0; 
          fi

          make image-build-env
      
      - name: Build Chaos Mesh Dev Env
        if: ${{ github.event.pull_request }}
        env:
          IMAGE_DEV_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-dev-env-image') }}
        run: |
          if [ "${IMAGE_DEV_ENV_BUILD}" = "true" ] ; then
            export IMAGE_DEV_ENV_BUILD=1; 
          else 
            export IMAGE_DEV_ENV_BUILD=0; 
          fi

          make image-dev-env

      - name: Install Chaos Mesh
        run: |
          export CLUSTER="chart-testing"
          hack/local-up-chaos-mesh.sh
          kubectl set env deployment/chaos-dashboard SECURITY_MODE=true -n chaos-testing
          kubectl set env deployment/chaos-controller-manager SECURITY_MODE=true -n chaos-testing
          sleep 5
          kubectl port-forward -n chaos-testing svc/chaos-dashboard 2333:2333 &
      - name: Make chaosctl
        run: |
          make chaosctl
      - name: Install localstack && aws client
        run: |
          helm repo add localstack-repo http://helm.localstack.cloud
          helm upgrade --install localstack localstack-repo/localstack --version 0.1.2
          pip install awscli

      - name: Run integration test
        run: |
          bash test/integration_test/run.sh
